### ISSUE TITLE
review music 29 patches for completeness 

### ISSUE THREAD

**Issue by equilet** [CNMAT/CNMAT-MMJ-Depot#40]

**Comment by mattschumaker** [comment]
test

**Comment by equilet** [comment]
@EdmundCampion - looks like there is a lab application missing for lab 07.  please advise.

**Comment by equilet** [comment]
Also: is the harmonicity vs inharmonicity patch/app used in M29 anymore?  If so, I think I need to give you either a separate standalone for that or we should tag a release based on this semester's class (if used as a patch).

**Comment by EdmundCampion** [comment]
The missing lab 07 is to hold the new MU29 module that is discussed in another issue thread -- the one where a source soundfile is mined for frequencies and then built into a model.  I can show you what is needed here and will do that in person.

**Comment by EdmundCampion** [comment]
Haronicity vs. inharmonicity patch should be used/added to Lab 01.  so yes, we need a test and standalone for that added to the current materials.

**Comment by mattschumaker** [comment]
@EdmundCampion @equilet 

Hello Ed and Jeff,

I have gone through all of the labs and tested them.  Overall, they seem to work very well.  However, I may have found some actionable items, which I will list below. Thanks for considering these.  If you want me to break these up into separate reports, by lab, please let me know.  (I am afraid that if I break them up now it will blitz both of you with many emails.)  I will also send Ed a separate email soon with a few other potential long term recommendations for possible minor alterations in the next class rev.

I plan to deliver the lab modules as they stand now to Willa in the lab tomorrow morning at 10 AM.  I am assuming that there is a way that we can make additions to the lab folders even after they are installed in the lab room.  However, if I am wrong about this and need to delay delivery for any reason, please call me and let me know.

Here below are my possibly actionable observations for this term:

LAB 1: Modes of Listening:
No impending issues

LAB 2: Hearing and Frequency:
No impending issues

Lab 3: Emotion and Music:
No impending issues

Lab 4:Construction-Production:
From Jeff's comment: The instructions and goals look a little incomplete.  Looks like we need sound file interpolation space.  Are we planning on using this for Lab 4?

LAB 5: Describing Sound:
Description file for Lab 5 says that it "needs to be fleshed out." Do we need to add to or alter this read me file before it comes up in lab?  If so, how to go about this? Regarding the musical selections, they all load properly and the lab as a whole seems to work well.  

LAB 6: Sonic Taxonomy:
No impending issues

LAB 7: Frequency Domain:
As remarked on in an email by Ed.  Text from the read me file included below.  How do we go about accomplishing this?

from the read me file:
create this lab with Jeff as follows: LAB 8  Bell Builder
Goal:  Model a bell using sinusoidal frequencies and sonogram analysis.
This LAB needs to be created from top to bottom.
The idea is to use the sonogram analysis on a selected bell sound (enclosed in folder).
The student "probes" the bell and locates frequencies and tunes them up to the bell.
then the student can turn off the bell sample and listen to the "chord" they have produced that mimics the bell.
This requires building a patch and new app…. to come.

LAB 8: Sonic Taxonomy:
I have some issues with the sampling portion of the polyrhythmic explorer patch but I don't know if it's just that I don't quite understand how to use it. In particular, using samples here is confusing for me.  Eventually, I figured out how to get sample sounds to play but, instead of playing the specific samples I had selected in the menus, the system always appeared to play random samples, regardless of whether or not the "shuffle samples" toggle is selected. 

Also, the patch directions refer to enabling the "view sample component" toggle but I could only find the "sample view front/back" toggle in the main patch.  Is this the same thing? 

LAB 9: Pitch Spaces:
Everything works well here.  However, it wasn't entirely clear to me from the read me file how students would interact with the patch.  Do instructors talk through and demonstrate the points on the read me files and then, between the two main sections of the lab, allow students to explore more freely around the concepts with the patches?

LAB 10: Group Composition:
Further clarification about the composition itself may be needed for instructors.  No technology involved in this lab.

LAB 11: Structural Analysis_I:

Do instructors or students  bring in their own sound files for the purposes of structural analysis I lab?  Or do they use sound files in other lab folders?  There are no sound files for analysis provided in this particular folder.

LAB 12: Structural Analysis_II:
Again, do instructors or students  bring in their own sound files for the purposes of structural analysis I lab?  Or do they use sound files in other lab folders?  There are no sound files for analysis provided in this particular folder.

**Comment by equilet** [comment]
the new stand-alones to be built will include a dsp init patch which should take care of the crashes we saw in https://github.com/CNMAT/CNMAT-MMJ-Depot/issues/61

**Comment by equilet** [comment]
There are far too many separate issues cluttered into this one space.  Let's make separate issues for each actionable item and in doing so, try to pinpoint the crucial developments that need to happen.
