### ISSUE TITLE
soundfile interpolation space - mp3 support

### ISSUE THREAD

**Issue by EdmundCampion** [CNMAT/CNMAT-MMJ-Depot#54]
Music 29 -- Soundfile_interpolation patch needs to be -mp3-enabled.
following the upgrade and testing, a new standalone needs to be made (both Windows and MAC)

**Comment by equilet** [comment]
get this to @mattschumaker by 14th of january

**Comment by equilet** [comment]
@mattschumaker - Can you please download the file found [here](http://www.dabkitsch.com/campion/mus29/standalones/debugging/SIS.zip) and let me know if it works for you?
Just report back in this issue here - if there is something to fix I will follow up, and if all looks good I'll build the Windows version.

**Comment by mattschumaker** [comment]
@equilet 

Hi Jeff,

I tested the new soundfile interpolation space standalone and it seems to work well.  Mp3s and wavefiles both play as expected, as far as I can hear, and all of the patch's functionality seemed to be working fine.  Awesome!

Here is one small, non-essential observation: when placing sounds into the space manually, I found it counter-intuitive to select a sound and then hit "place" again before positioning the sound in the 2d space.  I think that this is because "place" is already highlighted and so it seems like you should just be able to click in the environment and place the sound without hitting "place" again each time you grab a sound.  Again, certainly not very important.

When standalones are done for this, I will packages them in updated lab files for students to download from bcourses and also figure out how to replace the older modules inside the classroom labs.

Best,
Matt

**Comment by equilet** [comment]
I'm not going to change the functionality for placing the sound - I agree that this might not be the most intuitive, but I don't think this is a good time to work on that particular problem.  I'll build the windows version tonight based on your news.

**Comment by mattschumaker** [comment]
Great, thanks.  When it is available, I will get the updated version to the
students on bcourses right away. And we should be able to replace the lab
versions before that standalone comes up for the first time in lab 3.

Best,
Matt

**Comment by mattschumaker** [comment]
@equilet

Hi Jeff,
I think that I found a bug using the new soundfile space interpolation space today.  Sometimes when it loads a saved preset from disk the sound will not play at all.  For instance, in music 29 lab 3, if I load "01_emotional_inferences-solution.txt" all the sound will stop playing and it won't start back up again until I restart the app.

If this is a bug, then I think that we will just use the old version of the  soundfile interpolation space app for lab 3 starting on Friday.  We can change to an updated version for labs 4 or 6 later, if we want.

Best, Matt

**Comment by equilet** [comment]
this is unrelated to this issue - #54
