### ISSUE TITLE
lbyl

### ISSUE THREAD

**Issue by robinmeier** [CNMAT/CNMAT-MMJ-Depot#76]
hello, is there a version of lbyl that works in max7 64 bits? thanks! r

**Comment by equilet** [comment]
Hi Robin - lbyl has been deprecated, and is no longer included in the externals release.  FWIW, this repository you've filed in is exclusively for patches, rather than compiled externals.  

We reviewed this set carefully and decided that many of the objects we'd currently been supporting could be implemented either in MSP or Gen~.

See [this repository](https://github.com/CNMAT/CNMAT-Externs) for more info.
Thanks!
